name: Manual trigger
on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-22.04
    name: e2e-test
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Cypress test
        uses: cypress-io@github-action@v5
        with:
          command: npm usrun cy:run

