name: Manual trigger
on:
  workflow_dispatch

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Cypress run
        uses: cypress-io/github-action@v6
          command: npm run cy:run

