name: Pull Request Approval Workflow

on:
  pull_request_review:
    types: [submitted]

jobs:
  check_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's the first approval
        id: check_approval
        run: |
          pull_request_number=${{ github.event.pull_request.number }}
          commit_sha=${{ github.event.pull_request.head.sha }}

          # Fetch the list of approved reviews for the current pull request
          approved_reviews=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                              -H "Accept: application/vnd.github.v3+json" \
                              ${{ github.api_url }}/repos/${{ github.repository }}/pulls/$pull_request_number/reviews \
                              | jq '[.[] | select(.state == "APPROVED") | .commit_id]')

          # Fetch the list of commits in the pull request
          pull_request_commits=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                                   -H "Accept: application/vnd.github.v3+json" \
                                   ${{ github.api_url }}/repos/${{ github.repository }}/pulls/$pull_request_number/commits \
                                   | jq -r '.[].sha')

          # Check if the current commit is in the list of approved commits
          is_approved=$(echo "$approved_reviews" | jq -r ".[] | select(. == \"$commit_sha\")")

          # If the current commit is the first approved commit in the pull request, set the output to true
          if [ -n "$is_approved" ]; then
            echo "::set-output name=first_approval::true"
          else
            echo "::set-output name=first_approval::false"
          fi

      - name: Execute workflow if it's the first approval
        if: steps.check_approval.outputs.first_approval == 'true'
        run: |
          # Your workflow steps go here
          echo "Test Request Best"
