name: Check New Commits on Pull Request Review

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve Last Commit SHA
        id: last_commit
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Check if last commit SHA exists
        id: check_last_commit_sha
        run: |
          if [ -f last_commit_sha.txt ]; then
            echo "Last commit SHA exists."
            echo "::set-output name=exists::true"
          else
            echo "No previous commit SHA found. Assuming this is the first run."
            echo "::set-output name=exists::false"
          fi

      - name: Save commit SHA as an artifact
        if: steps.check_last_commit_sha.outputs.exists == 'false'
        run: echo "No previous commit SHA found. Skipping artifact upload."

      - name: Save commit SHA as an artifact
        if: steps.check_last_commit_sha.outputs.exists == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: last_commit_sha
          path: last_commit_sha.txt

      - name: Compare SHAs
        if: steps.check_last_commit_sha.outputs.exists == 'true'
        run: |
          LAST_SHA=$(cat last_commit_sha.txt)
          if [ "${LAST_SHA}" == "${{ steps.last_commit.outputs.sha }}" ]; then
            echo "No new commits since last job execution."
          else
            echo "New commits detected since last job execution."
            exit 1
          fi