on:
  pull_request_review:
    types: [submitted]

jobs:
  check_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if previous commit is different
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            # Fetch the previous commit SHA from GitHub API
            PREVIOUS_COMMIT=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$GITHUB_PULL_REQUEST/events" | jq '.[] | select(.event == "pull_request" and .commit_id != "'"$GITHUB_SHA"'") | .commit_id' | head -n 1 | tr -d '"')

            # Compare previous commit with current commit
            if [ "$PREVIOUS_COMMIT" != "" ]; then
              echo "Previous commit is different from current commit"
              # Do something here, like running additional checks or tasks
            else
              echo "Previous commit is the same as current commit"
            fi
          fi
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_PULL_REQUEST: ${{ github.event.pull_request.number }}