name: Check New Commits

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve Last Commit SHA
        id: last_commit
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Retrieve Current Head Commit SHA
        id: head_commit
        run: echo "::set-output name=sha::$(git ls-remote origin refs/pull/${{ github.event.pull_request.number }}/head | cut -f1)"

      - name: Compare SHAs
        run: |
          if [ "${{ steps.last_commit.outputs.sha }}" == "${{ steps.head_commit.outputs.sha }}" ]; then
            echo "No new commits since last job execution."
          else
            echo "New commits detected since last job execution."
          fi