name: Run on Pull Request Approval and Code Changes

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This step ensures the repository is checked out

      - name: Check if PR is approved and code has changed
        id: check-pr
        run: |
          # Check if the pull request is approved
          IS_APPROVED=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews?per_page=100" \
              | jq -r '.[] | select(.state == "APPROVED")' \
              | grep -c "id")
          # Check if there are code changes since last approval
          DIFF_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          if [ $IS_APPROVED -eq 1 ] && [ -n "$DIFF_FILES" ]; then
              echo "run_job=true" >> $GITHUB_ENV
          else
              echo "run_job=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Run Job if conditions met
        if: env.run_job == 'true'
        run: |
         echo 'test request'