on:
  pull_request_review:
    types: [submitted]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve Last Commit SHA
        id: last_commit
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Check if last commit SHA exists
        id: check_last_commit_sha
        run: |
          if [ -f last_commit_sha.txt ]; then
            echo "Last commit SHA exists."
            echo "::set-output name=exists::true"
          else
            echo "No previous commit SHA found. Assuming this is the first run."
            echo "::set-output name=exists::false"
          fi

      - name: Compare SHAs
        if: ${{ steps.check_last_commit_sha.outputs.exists == 'true' }}
        run: |
          if [ -f last_commit_sha.txt ]; then
            LAST_SHA=$(cat last_commit_sha.txt)
            if [ "${LAST_SHA}" == "${{ steps.last_commit.outputs.sha }}" ]; then
              echo "No new commits since last job execution."
            else
              echo "New commits detected since last job execution."
            fi
          else
            echo "No previous commit SHA found. Skipping comparison."
          fi

      - name: Save last commit SHA as artifact
        run: |
          echo "${{ steps.last_commit.outputs.sha }}" > last_commit_sha.txt
        shell: bash
      
      - name: Upload last commit SHA as artifact
        uses: actions/upload-artifact@v2
        with:
          name: last_commit_sha
          path: last_commit_sha.txt